### PR TITLE
support 2.0, all planet, more entities, refactoring

### PR DESCRIPTION
**Pull request by eugenikus8**
I'll help you a little with the code. I got the mod to work. True, I changed the code completely. But now it works on all planets and with many entities. I changed the folder name, but you can change everything back.

[Turret_Alerts.zip](https://github.com/user-attachments/files/17533360/Turret_Alerts.zip)

### CODE REVIEW

**Comment by Wyrrrd** [comment]
Oh boy... Thanks for your work, but I have questions:

- Why did you drop my event optimization for scanning the whole surface again? I can currently renew the alerts every 10s while you need to wait a whole minute (to avoid having lag spikes too often, I guess)
- Why did you drop the low ammo icon?
- Have you thought about how players might only want to be informed about low ammo on the planet they are on? I'd rather not force the alerts of all surfaces on them, since that's not how the mod worked in 1.1
- Why are the enable settings global now? There's no need to force players to restart the save if they want to change the behavior. (Also in multiplayer, this means all players have to have the same settings.)
- Why did you drop working with forces? If players play a game against each other, they probably don't want the enemy player to be informed whenever their turrets are low or empty.

**Comment by eugenikus8** [comment]
> Why did you drop my event optimization for scanning the whole surface again? I can currently renew the alerts every 10s while you need to wait a whole minute (to avoid having lag spikes too often, I guess)

In my version 600/60=10sec

> Why did you drop the low ammo icon?

Sorry, just wanted to reduce the size of the mod. But I can return

> Have you thought about how players might only want to be informed about low ammo on the planet they are on? I'd rather not force the alerts of all surfaces on them, since that's not how the mod worked in 1.1

I'll make 2 additional settings for this soon

> Why are the enable settings global now? There's no need to force players to restart the save if they want to change the behavior. (Also in multiplayer, this means all players have to have the same settings.)

Settings in the map tab

> * Why did you drop working with forces? If players play a game against each other, they probably don't want the enemy player to be informed whenever their turrets are low or empty.

Difficult. But where can I test if I can do it?

**Comment by eugenikus8** [comment]
Are you planning to update this mod or should I not continue further?

**Comment by Wyrrrd** [comment]
Sorry about the time miscalculation, my bad. I plan on updating the mod, but you can do what you want of course.

I will not merge your changes as is, but I suggest you upload it to the mod portal under another name instead (be sure to add what the license demands), since yours is better than not having any such functionality.

I'll ping you when I updated, so you can decide if you keep or deprecate your mod then :)

**Comment by Wyrrrd** [comment]
Oops, that went faster than I thought...

https://github.com/Wyrrrd/Gun_Turret_Alerts/releases/tag/v2.0.0

If you still want to add the russian locale, you can open a separate PR :)

**Pull request closed without merging**
